apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  type: Scala
  mode: cluster
  sparkVersion: "3.5.5"
  image: ${IMAGE}
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkSQLCli
  mainApplicationFile: local:///opt/spark-sql/jas/spark-sql.jar
  arguments:
    - |
        ${ARGUMENTS}
  restartPolicy:
    type: Never

  sparkConf:
    spark.eventLog.enabled: "false"
    spark.eventLog.dir: "/tmp"
  deps:
    jars: ${JARS}
  volumes:
    - name: datas
      hostPath:
        path: /tmp/spark_dep_jars

  driver:
    labels:
      dolphinscheduler-label: ${DRIVER_LABEL}
    cores: ${DRIVER_CORES}
    memory: ${DRIVER_MEMORY}
    serviceAccount: ${SERVICE_ACCOUNT}
    volumeMounts:
      - name: datas
        mountPath: /mnt/spark_dep_jars/

  executor:
    cores: ${EXECUTOR_CORES}
    instances: ${NUM_EXECUTORS}
    memory: ${EXECUTOR_MEMORY}
    volumeMounts:
      - name: datas
        mountPath: /mnt/spark_dep_jars/